version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - absensi

networks:
  absensi:

volumes:
  pgdata: